# Generated by Django 5.0.1 on 2024-01-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Please enter a valid email address.', max_length=254, unique=True),
        ),
    ]
