# Generated by Django 5.0.1 on 2024-01-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_storetype_store_address_store_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_app.storetype', verbose_name='Store Type'),
            preserve_default=False,
        ),
    ]
